require 'pry'
require 'net/http'
require 'open-uri'
require 'json'
require 'colorize'
require 'tty-prompt'

require_relative '../lib/modules/crypto.rb'
require_relative '../lib/api'
require_relative '../lib/cli'
require_relative '../lib/cryptocurrency'
require_relative '../lib/cryptocurrency_search'
require_relative '../lib/status'
